platform :ios, '10.0'

target 'Flash Chat iOS13' do
  use_frameworks!

  # Pods for Flash Chat iOS13
  
  # CLTyping Label pod
  pod 'CLTypingLabel', '~> 0.4.0'
  
  # firebase pods
  pod 'Firebase/Auth'
  pod 'Firebase/Firestore'

end
